const screens={cats:document.getElementById('categoriesScreen'),q:document.getElementById('questionScreen')};
const data={evening:{title:'Вечер для двоих',count:36,questions:[['Какой момент\nиз детства сформировал\nтебя больше всего?','Расскажи, что сделал тебя тем, кто ты есть сегодня.'],['Что рядом со мной\nделает твой вечер\nтеплее?','Можно ответить одной деталью, жестом или воспоминанием.'],['Какой наш разговор\nты хотел бы\nповторить?','Вспомни момент, где вы стали ближе.'],['Что я делаю так,\nчто тебе становится\nспокойнее?','Назови что-то маленькое, но важное.']]},fight:{title:'После ссоры',count:24,questions:[['Что тебе сейчас\nважнее всего\nуслышать от меня?','Скажи спокойно и честно, без обвинений.'],['Где я мог\nпонять тебя\nнеправильно?','Попробуйте найти не виноватого, а смысл.']]}};
let current='evening', index=0;
function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
function buildProgress(){const p=document.getElementById('progress');p.innerHTML='';for(let i=0;i<10;i++){const dot=document.createElement('i');if(i<=Math.min(9,index))dot.className='done';p.append(dot)}}
function render(){const cat=data[current];const q=cat.questions[index%cat.questions.length];document.getElementById('qCategory').textContent=cat.title;document.getElementById('qSub').textContent=`Вопрос ${index+1} из ${cat.count}`;document.getElementById('qText').innerHTML=q[0].replaceAll('\n','<br>');document.getElementById('qHint').textContent=q[1];buildProgress();}
function start(cat){current=cat;index=3;render();show('q')}
function next(){index=(index+1)%data[current].questions.length;render();const card=document.getElementById('questionCard');card.animate([{transform:'translateY(0)',opacity:1},{transform:'translateY(-18px)',opacity:.65},{transform:'translateY(0)',opacity:1}],{duration:310,easing:'cubic-bezier(.2,.8,.2,1)'})}
document.querySelectorAll('[data-start]').forEach(b=>b.onclick=e=>start(e.currentTarget.dataset.start));document.getElementById('backBtn').onclick=()=>show('cats');document.getElementById('navCats').onclick=()=>show('cats');document.getElementById('nextBtn').onclick=next;let sy=0;document.addEventListener('touchstart',e=>sy=e.touches[0].clientY,{passive:true});document.addEventListener('touchend',e=>{const dy=e.changedTouches[0].clientY-sy;if(screens.q.classList.contains('active')&&dy<-55)next();},{passive:true});
